name: Packer Build AMI

on:
  push:
    branches:
      - main
      - JuanFeatures
    paths:
      - 'packer/**'
      - 'ansible/**'
  workflow_dispatch: # Permite ejecución manual desde la pestaña Actions en GitHub

permissions:
  id-token: write # Requerido para autenticación mediante OIDC
  contents: read

jobs:
  packer-build:
    name: Build AWS AMI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configurar HashiCorp Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: 'latest'

      - name: Instalar Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Inicializar y Validar Packer
        run: |
          cd packer
          packer init aws-ubuntu.pkr.hcl
          packer validate aws-ubuntu.pkr.hcl

      - name: Construir la AMI con Packer
        run: |
          cd packer
          packer build aws-ubuntu.pkr.hcl